[package]
name = "stockfish_studio"
version = "0.1.0"
edition = "2024"

[dependencies]
wry = { version = "0.53.5", default-features = false, features = ["devtools"] }
tao = { version = "0.34", default-features = false, features = ["rwh_06"] }
anyhow = "1.0"
url = "2.5"
